<a href="https://colab.research.google.com/github/neel-madhav/TensorFlowLearning/blob/main/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

#Tensor Initialization

In [2]:
tensor_0D = tf.constant(4)
print(tensor_0D)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_1D = tf.constant([2, 0, -3])
print(tensor_1D)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [4]:
tensor_2D = tf.constant([[1, 2, 0], [0, 2, -2]])
print(tensor_2D)

tf.Tensor(
[[ 1  2  0]
 [ 0  2 -2]], shape=(2, 3), dtype=int32)


In [7]:
tensor_3D = tf.constant([[[1,2,0], [3,4,5]], [[5,8,0],[2,7,0]], [[10, 2, 0], [1, 0, 2]], [[1,3,0], [3,5,-1]]] , dtype=tf.float32)
print(tensor_3D)

tf.Tensor(
[[[ 1.  2.  0.]
  [ 3.  4.  5.]]

 [[ 5.  8.  0.]
  [ 2.  7.  0.]]

 [[10.  2.  0.]
  [ 1.  0.  2.]]

 [[ 1.  3.  0.]
  [ 3.  5. -1.]]], shape=(4, 2, 3), dtype=float32)


In [10]:
tensor_2D = tf.constant([[1, 2, 0], [0, 2, -2]], dtype = tf.float32)
casted = tf.cast(tensor_2D, tf.int32)
print(casted)
print(tensor_2D)

tf.Tensor(
[[ 1  2  0]
 [ 0  2 -2]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1.  2.  0.]
 [ 0.  2. -2.]], shape=(2, 3), dtype=float32)


In [11]:
tensor_bool=([True, True, False])
print(tensor_bool)

[True, True, False]


In [12]:
tensor_string = tf.constant(["hello world", "hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [13]:
import numpy as np

In [14]:
np_array = np.array([[1,2,3], [4,5,6]])
print(np_array)

[[1 2 3]
 [4 5 6]]


In [15]:
converted = tf.convert_to_tensor(np_array)
print(converted)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)


In [16]:
eye_tensor = tf.eye(num_rows = 3, num_columns = None, batch_shape = None, name = None, dtype=tf.dtypes.float32)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
eye_tensor = tf.eye(num_rows = 5, num_columns = 3, batch_shape = None, name = None, dtype=tf.dtypes.float32)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [20]:
eye_tensor = tf.eye(num_rows = 3, num_columns = None, batch_shape = [2], name = None, dtype=tf.dtypes.float32)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [23]:
fill_tensor = tf.fill([2,3,4], 5, name = None)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [27]:
fill_ones = tf.ones([3,4], dtype=tf.dtypes.float32, name = None)
print(fill_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [28]:
ones_like_tensor = tf.ones_like(fill_ones)
print(ones_like_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [31]:
fill_zeroes = tf.zeros([3,4], dtype=tf.dtypes.float32, name = None)
print(fill_zeroes)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [32]:
print(tf.shape(fill_zeroes))

tf.Tensor([3 4], shape=(2,), dtype=int32)


In [34]:
t = tf.constant([[[1,2,0], [3,4,5]], [[5,8,0],[2,7,0]], [[10, 2, 0], [1, 0, 2]], [[1,3,0], [3,5,-1]]] , dtype=tf.float32)
print(tf.rank(t))
print(tf.size(t))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(24, shape=(), dtype=int32)


In [36]:
random_tensor = tf.random.normal([3,2], mean = 0.0, stddev = 1.0, dtype = tf.dtypes.float32, seed = None, name = None)
print(random_tensor)

tf.Tensor(
[[-1.6913795  -2.9419827 ]
 [-0.9075992   0.55288994]
 [-2.7123554   0.59127647]], shape=(3, 2), dtype=float32)


In [38]:
random_tensor = tf.random.uniform([3,2], minval = 0, maxval = 100, dtype = tf.dtypes.float32, seed = None, name = None)
print(random_tensor)

tf.Tensor(
[[88.19263  36.897133]
 [73.42803  84.84974 ]
 [74.05069  82.49456 ]], shape=(3, 2), dtype=float32)


In [46]:
tf.random.set_seed(5)
print(tf.random.uniform([2,3], minval = 0, maxval = 3, dtype = tf.dtypes.int32, seed = 1, name = None))


tf.Tensor(
[[0 1 2]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [49]:
tf.random.set_seed(5)
print(tf.random.uniform([2,3], minval = 0, maxval = 3, dtype = tf.dtypes.int32, seed = 10, name = None))


tf.Tensor(
[[2 0 1]
 [2 1 1]], shape=(2, 3), dtype=int32)


In [52]:

print(tf.random.uniform([2,3], minval = 0, maxval = 3, dtype = tf.dtypes.int32, seed = 1, name = None))


tf.Tensor(
[[1 0 1]
 [2 1 0]], shape=(2, 3), dtype=int32)


#Indexing

In [62]:
index = tf.constant([1,2,3,4,5,6,7,8,9,0])
print(index[0])
print(index[-1])
print(index[1:6])
print(index[:6])
print(index[1:])
print(index[2:-1])
print(index[5:-2])
print(index[:10:2])


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([2 3 4 5 6 7 8 9 0], shape=(9,), dtype=int32)
tf.Tensor([3 4 5 6 7 8 9], shape=(7,), dtype=int32)
tf.Tensor([6 7 8], shape=(3,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [69]:
index2D = tf.constant([[1,2,3], [4,5,6],[7,8,9]])
print(index2D[1,2])
print(index2D[1,:])
print(index2D[0,:])
print(index2D[0:1,:])

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


#Math Operation

In [71]:
x = tf.constant(-0.2)
print(tf.abs(x))

tf.Tensor(0.2, shape=(), dtype=float32)


In [72]:
y = tf.constant([[1,-2.0, 4, -3,7], [-7, 8, -3.46, -9, 5]])
print(tf.abs(y))

tf.Tensor(
[[1.   2.   4.   3.   7.  ]
 [7.   8.   3.46 9.   5.  ]], shape=(2, 5), dtype=float32)


In [73]:
z = tf.constant([3-5j, 4+2j, 7+8j, -9+10j])
print(tf.abs(z))

tf.Tensor([ 5.83095189  4.47213595 10.63014581 13.45362405], shape=(4,), dtype=float64)


In [78]:
print(tf.sqrt(3.**2+5.**2))

tf.Tensor(5.8309517, shape=(), dtype=float32)


In [80]:
x = tf.constant([1,2,3,4,5])
y = tf.constant([6,7,8,9,0])
tf.add(x,y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 7,  9, 11, 13,  5], dtype=int32)>

In [84]:
x = tf.constant(10)
y = tf.constant(0)
print(tf.divide(x,y))
print(tf.math.divide(x,y))
print(tf.math.divide_no_nan(x,y))

tf.Tensor(inf, shape=(), dtype=float64)
tf.Tensor(inf, shape=(), dtype=float64)
tf.Tensor(0.0, shape=(), dtype=float64)


In [88]:
x = tf.constant([[1,2,3],[3,4,5],[7,8,9]])
y = tf.constant([[1],[2],[3]])
print(tf.multiply(y,x))

tf.Tensor(
[[ 1  2  3]
 [ 6  8 10]
 [21 24 27]], shape=(3, 3), dtype=int32)


In [90]:
x = tf.constant([[1,8,3],[7,4,5],[2,3,9]])
print(tf.argmax(x))

tf.Tensor([1 0 2], shape=(3,), dtype=int64)


In [93]:
x = tf.constant([[1,8,3],[7,4,5],[2,3,9]])
y = tf.constant([[1,8,2],[7,8,5],[2,10,9]])
print(tf.math.equal(x, y))

tf.Tensor(
[[ True  True False]
 [ True False  True]
 [ True False  True]], shape=(3, 3), dtype=bool)


In [100]:
print(tf.math.reduce_max(x))
print(tf.math.reduce_sum(x))
print(tf.math.reduce_sum(x, axis = None, keepdims = True))
print(tf.math.reduce_sum(x, axis = None, keepdims = False))

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(42, shape=(), dtype=int32)
tf.Tensor([[42]], shape=(1, 1), dtype=int32)
tf.Tensor(42, shape=(), dtype=int32)


In [102]:
print(tf.math.top_k([1,2,3,4,5,6,7,8,9], k = 3
                    ))

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 8, 7], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([8, 7, 6], dtype=int32)>)


In [104]:
x=tf.constant([1,2.0,3,4,5,6,7,8,9,0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.73105854, 0.8807971 , 0.95257413, 0.98201376, 0.9933072 ,
       0.99752736, 0.99908894, 0.99966466, 0.9998766 , 0.5       ],
      dtype=float32)>

#Linear Algebra


In [112]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[1,3],[2,4]])
print(tf.linalg.matmul(a,b))

tf.Tensor(
[[ 5 11]
 [11 25]], shape=(2, 2), dtype=int32)
